<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Errors;

class InitiateOauth2SigninCarrierAccountsResponseResponseBodyThrowable extends \RuntimeException
{
    public InitiateOauth2SigninCarrierAccountsResponseResponseBody $container;

    public function __construct(string $message, int $statusCode, InitiateOauth2SigninCarrierAccountsResponseResponseBody $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}