workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi:
        inputs:
            - location: https://docs.goshippo.com/spec/shippoapi/public-api.yaml
        registry:
            location: registry.speakeasyapi.dev/shippo/shippo/openapi
targets:
    my-first-target:
        target: php
        source: openapi
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/shippo/shippo/openapi-code-samples
            blocking: false
