<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Operations;

use Shippo\API\Models\Components;
use Shippo\API\Utils\SpeakeasyMetadata;
class CreateServiceGroupRequest
{
    /**
     *
     * @var \Shippo\API\Models\Components\ServiceGroupCreateRequest $serviceGroupCreateRequest
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\ServiceGroupCreateRequest $serviceGroupCreateRequest;

    /**
     * Optional string used to pick a non-default API version to use. See our [API version](https://docs.goshippo.com/docs/api_concepts/apiversioning/) guide.
     *
     * @var ?string $shippoApiVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=SHIPPO-API-VERSION')]
    public ?string $shippoApiVersion = null;

    /**
     * @param  \Shippo\API\Models\Components\ServiceGroupCreateRequest  $serviceGroupCreateRequest
     * @param  ?string  $shippoApiVersion
     * @phpstan-pure
     */
    public function __construct(Components\ServiceGroupCreateRequest $serviceGroupCreateRequest, ?string $shippoApiVersion = '2018-02-08')
    {
        $this->serviceGroupCreateRequest = $serviceGroupCreateRequest;
        $this->shippoApiVersion = $shippoApiVersion;
    }
}