<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Operations;

use Shippo\API\Models\Components;
use Shippo\API\Utils\SpeakeasyMetadata;
class CreateEmbeddedAuthorizationRequest
{
    /**
     * The scope to request for the token.
     *
     * @var \Shippo\API\Models\Components\EmbeddedAuthorizationRequest $embeddedAuthorizationRequest
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\EmbeddedAuthorizationRequest $embeddedAuthorizationRequest;

    /**
     * Optional. The object ID of a Managed Shippo Account. Platform accounts set this to
     *
     * mint a JWT scoped to one of their managed accounts.
     *
     * @var ?string $shippoAccountId
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=SHIPPO-ACCOUNT-ID')]
    public ?string $shippoAccountId = null;

    /**
     * Optional string used to pick a non-default API version to use. See our [API version](https://docs.goshippo.com/docs/api_concepts/apiversioning/) guide.
     *
     * @var ?string $shippoApiVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=SHIPPO-API-VERSION')]
    public ?string $shippoApiVersion = null;

    /**
     * @param  \Shippo\API\Models\Components\EmbeddedAuthorizationRequest  $embeddedAuthorizationRequest
     * @param  ?string  $shippoApiVersion
     * @param  ?string  $shippoAccountId
     * @phpstan-pure
     */
    public function __construct(Components\EmbeddedAuthorizationRequest $embeddedAuthorizationRequest, ?string $shippoAccountId = null, ?string $shippoApiVersion = '2018-02-08')
    {
        $this->embeddedAuthorizationRequest = $embeddedAuthorizationRequest;
        $this->shippoAccountId = $shippoAccountId;
        $this->shippoApiVersion = $shippoApiVersion;
    }
}