<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Operations;

use Shippo\API\Models\Components;
use Shippo\API\Utils\SpeakeasyMetadata;
class CreateUserParcelTemplateRequest
{
    /**
     *
     * @var Components\UserParcelTemplateWithCarrierTemplateCreateRequest|Components\UserParcelTemplateWithoutCarrierTemplateCreateRequest $userParcelTemplateCreateRequest
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\UserParcelTemplateWithCarrierTemplateCreateRequest|Components\UserParcelTemplateWithoutCarrierTemplateCreateRequest $userParcelTemplateCreateRequest;

    /**
     * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
     *
     * @var ?string $shippoApiVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=SHIPPO-API-VERSION')]
    public ?string $shippoApiVersion = null;

    /**
     * @param  Components\UserParcelTemplateWithCarrierTemplateCreateRequest|Components\UserParcelTemplateWithoutCarrierTemplateCreateRequest  $userParcelTemplateCreateRequest
     * @param  ?string  $shippoApiVersion
     * @phpstan-pure
     */
    public function __construct(Components\UserParcelTemplateWithCarrierTemplateCreateRequest|Components\UserParcelTemplateWithoutCarrierTemplateCreateRequest $userParcelTemplateCreateRequest, ?string $shippoApiVersion = null)
    {
        $this->userParcelTemplateCreateRequest = $userParcelTemplateCreateRequest;
        $this->shippoApiVersion = $shippoApiVersion;
    }
}