<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Operations;

use Shippo\API\Models\Components;
use Shippo\API\Utils\SpeakeasyMetadata;
class CreateTransactionRequest
{
    /**
     * Examples.
     *
     * @var \Shippo\API\Models\Components\TransactionCreateRequest|\Shippo\API\Models\Components\InstantTransactionCreateRequest $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\TransactionCreateRequest|Components\InstantTransactionCreateRequest $requestBody;

    /**
     * Optional string used to pick a non-default API version to use. See our [API version](https://docs.goshippo.com/docs/api_concepts/apiversioning/) guide.
     *
     * @var ?string $shippoApiVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=SHIPPO-API-VERSION')]
    public ?string $shippoApiVersion = null;

    /**
     * @param  \Shippo\API\Models\Components\TransactionCreateRequest|\Shippo\API\Models\Components\InstantTransactionCreateRequest  $requestBody
     * @param  ?string  $shippoApiVersion
     * @phpstan-pure
     */
    public function __construct(Components\TransactionCreateRequest|Components\InstantTransactionCreateRequest $requestBody, ?string $shippoApiVersion = '2018-02-08')
    {
        $this->requestBody = $requestBody;
        $this->shippoApiVersion = $shippoApiVersion;
    }
}