<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Operations;

use Shippo\API\Models\Components;
use Shippo\API\Utils\SpeakeasyMetadata;
class CreateRefundRequest
{
    /**
     * Refund details
     *
     * @var Components\RefundRequestBody $refundRequestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\RefundRequestBody $refundRequestBody;

    /**
     * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
     *
     * @var ?string $shippoApiVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=SHIPPO-API-VERSION')]
    public ?string $shippoApiVersion = null;

    /**
     * @param  Components\RefundRequestBody  $refundRequestBody
     * @param  ?string  $shippoApiVersion
     * @phpstan-pure
     */
    public function __construct(Components\RefundRequestBody $refundRequestBody, ?string $shippoApiVersion = null)
    {
        $this->refundRequestBody = $refundRequestBody;
        $this->shippoApiVersion = $shippoApiVersion;
    }
}