<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Operations;

use Shippo\API\Models\Components;
use Shippo\API\Utils\SpeakeasyMetadata;
class CreatePickupRequest
{
    /**
     * Shippo’s pickups endpoint allows you to schedule pickups with USPS and DHL Express for eligible shipments that you have already created.
     *
     * @var Components\PickupBase $pickupBase
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\PickupBase $pickupBase;

    /**
     * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
     *
     * @var ?string $shippoApiVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=SHIPPO-API-VERSION')]
    public ?string $shippoApiVersion = null;

    /**
     * @param  Components\PickupBase  $pickupBase
     * @param  ?string  $shippoApiVersion
     * @phpstan-pure
     */
    public function __construct(Components\PickupBase $pickupBase, ?string $shippoApiVersion = null)
    {
        $this->pickupBase = $pickupBase;
        $this->shippoApiVersion = $shippoApiVersion;
    }
}