<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Operations;

use Shippo\API\Utils\SpeakeasyMetadata;
class GetCustomsItemRequest
{
    /**
     * Object ID of the customs item
     *
     * @var string $customsItemId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=CustomsItemId')]
    public string $customsItemId;

    /**
     * The page number you want to select
     *
     * @var ?int $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;

    /**
     * String used to pick a non-default API version to use
     *
     * @var ?string $shippoApiVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=SHIPPO-API-VERSION')]
    public ?string $shippoApiVersion = null;

    public function __construct()
    {
        $this->customsItemId = '';
        $this->page = null;
        $this->shippoApiVersion = null;
    }
}