<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Operations;

use Shippo\API\Utils\SpeakeasyMetadata;
class GetCustomsItemRequest
{
    /**
     * Object ID of the customs item
     *
     * @var string $customsItemId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=CustomsItemId')]
    public string $customsItemId;

    /**
     * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
     *
     * @var ?string $shippoApiVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=SHIPPO-API-VERSION')]
    public ?string $shippoApiVersion = null;

    /**
     * The page number you want to select
     *
     * @var ?int $page
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;

    /**
     * @param  string  $customsItemId
     * @param  ?int  $page
     * @param  ?string  $shippoApiVersion
     */
    public function __construct(string $customsItemId, ?string $shippoApiVersion = null, ?int $page = 1)
    {
        $this->customsItemId = $customsItemId;
        $this->shippoApiVersion = $shippoApiVersion;
        $this->page = $page;
    }
}