<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Operations;

use Shippo\API\Utils\SpeakeasyMetadata;
class GetManifestRequest
{
    /**
     * Object ID of the manifest to update
     *
     * @var string $manifestId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=ManifestId')]
    public string $manifestId;

    /**
     * Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.
     *
     * @var ?string $shippoApiVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=SHIPPO-API-VERSION')]
    public ?string $shippoApiVersion = null;

    /**
     * @param  string  $manifestId
     * @param  ?string  $shippoApiVersion
     */
    public function __construct(string $manifestId, ?string $shippoApiVersion = null)
    {
        $this->manifestId = $manifestId;
        $this->shippoApiVersion = $shippoApiVersion;
    }
}