<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Operations;

use Shippo\API\Utils\SpeakeasyMetadata;
class GetTransactionRequest
{
    /**
     * Object ID of the transaction to update
     *
     * @var string $transactionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=TransactionId')]
    public string $transactionId;

    /**
     * Optional string used to pick a non-default API version to use. See our [API version](https://docs.goshippo.com/docs/api_concepts/apiversioning/) guide.
     *
     * @var ?string $shippoApiVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=SHIPPO-API-VERSION')]
    public ?string $shippoApiVersion = null;

    /**
     * @param  string  $transactionId
     * @param  ?string  $shippoApiVersion
     * @phpstan-pure
     */
    public function __construct(string $transactionId, ?string $shippoApiVersion = '2018-02-08')
    {
        $this->transactionId = $transactionId;
        $this->shippoApiVersion = $shippoApiVersion;
    }
}