<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Operations;

use Shippo\API\Models\Components;
use Shippo\API\Utils\SpeakeasyMetadata;
class UpdateUserParcelTemplateRequest
{
    /**
     * Object ID of the user parcel template
     *
     * @var string $userParcelTemplateObjectId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=UserParcelTemplateObjectId')]
    public string $userParcelTemplateObjectId;

    /**
     *
     * @var ?\Shippo\API\Models\Components\UserParcelTemplateUpdateRequest $userParcelTemplateUpdateRequest
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?Components\UserParcelTemplateUpdateRequest $userParcelTemplateUpdateRequest = null;

    /**
     * Optional string used to pick a non-default API version to use. See our [API version](https://docs.goshippo.com/docs/api_concepts/apiversioning/) guide.
     *
     * @var ?string $shippoApiVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=SHIPPO-API-VERSION')]
    public ?string $shippoApiVersion = null;

    /**
     * @param  string  $userParcelTemplateObjectId
     * @param  ?string  $shippoApiVersion
     * @param  ?\Shippo\API\Models\Components\UserParcelTemplateUpdateRequest  $userParcelTemplateUpdateRequest
     * @phpstan-pure
     */
    public function __construct(string $userParcelTemplateObjectId, ?Components\UserParcelTemplateUpdateRequest $userParcelTemplateUpdateRequest = null, ?string $shippoApiVersion = '2018-02-08')
    {
        $this->userParcelTemplateObjectId = $userParcelTemplateObjectId;
        $this->userParcelTemplateUpdateRequest = $userParcelTemplateUpdateRequest;
        $this->shippoApiVersion = $shippoApiVersion;
    }
}