<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class AddressValidationResultsMessage
{
    /**
     * See <a href="#tag/Address-Validation-Codes">Address Validation Codes</a>
     *
     * @var ?string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $code = null;

    /**
     * See <a href="#tag/Address-Validation-Source">Address Validation Source</a>
     *
     * @var ?string $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $source = null;

    /**
     *
     * @var ?string $text
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('text')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $text = null;

    /**
     *
     * @var ?string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     * @param  ?string  $code
     * @param  ?string  $source
     * @param  ?string  $text
     * @param  ?string  $type
     * @phpstan-pure
     */
    public function __construct(?string $code = null, ?string $source = null, ?string $text = null, ?string $type = null)
    {
        $this->code = $code;
        $this->source = $source;
        $this->text = $text;
        $this->type = $type;
    }
}