<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/** AddressCreateRequest - Address represents the address as retrieved from the database */
class AddressCreateRequest
{
    /**
     * ISO 3166-1 alpha-2 country codes and country names can be used. For most consistent results, we reccomend using country codes like `US` or `DE`.
     *
     * If using country names, please ensure they are spelled correctly and in English. Country names are converted to country codes.
     * Refer to this <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements" target="_blank">guide</a> for a list of country codes.
     * Sending a country is always required.
     *
     * @var string $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    public string $country;

    /**
     * **required for purchase**<br>
     *
     * First and Last Name of the addressee
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * Company Name
     *
     * @var ?string $company
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('company')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $company = null;

    /**
     * **required for purchase**<br>
     *
     * First street line, 35 character limit. Usually street number and street name (except for DHL Germany, see street_no).
     *
     * @var ?string $street1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('street1')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $street1 = null;

    /**
     * Second street line, 35 character limit.
     *
     * @var ?string $street2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('street2')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $street2 = null;

    /**
     * Third street line, 35 character limit. 
     *
     * Only accepted for USPS international shipments, UPS domestic and UPS international shipments.
     *
     * @var ?string $street3
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('street3')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $street3 = null;

    /**
     * Street number of the addressed building. 
     *
     * This field can be included in street1 for all carriers except for DHL Germany.
     *
     * @var ?string $streetNo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('street_no')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $streetNo = null;

    /**
     * **required for purchase**<br>
     *
     * Name of a city. When creating a Quote Address, sending a city is optional but will yield more accurate Rates. 
     * Please bear in mind that city names may be ambiguous (there are 34 Springfields in the US). Pass in a state 
     * or a ZIP code (see below), if known, it will yield more accurate results.
     *
     * @var ?string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $city = null;

    /**
     * **required for purchase for some countries**<br>
     *
     * State/Province values are required for shipments from/to the US, AU, and CA. UPS requires province for some 
     * countries (i.e Ireland). To receive more accurate quotes, passing this field is recommended. Most carriers 
     * only accept two or three character state abbreviations.
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     * **required for purchase**<br>
     *
     * Postal code of an Address. When creating a Quote Addresses, sending a ZIP is optional but will yield more 
     * accurate Rates.
     *
     * @var ?string $zip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('zip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $zip = null;

    /**
     * Addresses containing a phone number allow carriers to call the recipient when delivering the Parcel. This 
     *
     * increases the probability of delivery and helps to avoid accessorial charges after a Parcel has been shipped.    
     *
     * @var ?string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phone = null;

    /**
     * E-mail address of the contact person, RFC3696/5321-compliant.
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     *
     * @var ?bool $isResidential
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_residential')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isResidential = null;

    /**
     * A string of up to 100 characters that can be filled with any additional information you want 
     *
     * to attach to the object.
     *
     * @var ?string $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $metadata = null;

    /**
     * Set to true to validate Address object.
     *
     * @var ?bool $validate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('validate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $validate = null;

    /**
     * @param  string  $country
     * @param  ?string  $name
     * @param  ?string  $company
     * @param  ?string  $street1
     * @param  ?string  $street2
     * @param  ?string  $street3
     * @param  ?string  $streetNo
     * @param  ?string  $city
     * @param  ?string  $state
     * @param  ?string  $zip
     * @param  ?string  $phone
     * @param  ?string  $email
     * @param  ?bool  $isResidential
     * @param  ?string  $metadata
     * @param  ?bool  $validate
     */
    public function __construct(string $country, ?string $name = null, ?string $company = null, ?string $street1 = null, ?string $street2 = null, ?string $street3 = null, ?string $streetNo = null, ?string $city = null, ?string $state = null, ?string $zip = null, ?string $phone = null, ?string $email = null, ?bool $isResidential = null, ?string $metadata = null, ?bool $validate = null)
    {
        $this->country = $country;
        $this->name = $name;
        $this->company = $company;
        $this->street1 = $street1;
        $this->street2 = $street2;
        $this->street3 = $street3;
        $this->streetNo = $streetNo;
        $this->city = $city;
        $this->state = $state;
        $this->zip = $zip;
        $this->phone = $phone;
        $this->email = $email;
        $this->isResidential = $isResidential;
        $this->metadata = $metadata;
        $this->validate = $validate;
    }
}