<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class Authentication
{
    /**
     * Authentication method used by this account.
     *
     * @var ?CarrierAccountWithExtraInfoType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CarrierAccountWithExtraInfoType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CarrierAccountWithExtraInfoType $type = null;

    /**
     * Current authentication status. Possible values: 'disconnected' (authorization lost, reconnect needed), 'connected' (authorized and active), 'authorization_pending' (awaiting initial authorization flow).
     *
     * @var ?CarrierAccountWithExtraInfoStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CarrierAccountWithExtraInfoStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CarrierAccountWithExtraInfoStatus $status = null;

    /**
     * @param  ?CarrierAccountWithExtraInfoType  $type
     * @param  ?CarrierAccountWithExtraInfoStatus  $status
     */
    public function __construct(?CarrierAccountWithExtraInfoType $type = null, ?CarrierAccountWithExtraInfoStatus $status = null)
    {
        $this->type = $type;
        $this->status = $status;
    }
}