<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/** The type of building where the pickup is located. */
enum BuildingType: string
{
    case Apartment = 'apartment';
    case Building = 'building';
    case Department = 'department';
    case Floor = 'floor';
    case Room = 'room';
    case Suite = 'suite';
}
