<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class CarrierAccountUPSCreateRequestParameters
{
    /**
     *
     * @var string $billingAddressCity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address_city')]
    public string $billingAddressCity;

    /**
     *
     * @var string $billingAddressCountryIso2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address_country_iso2')]
    public string $billingAddressCountryIso2;

    /**
     *
     * @var string $billingAddressState
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address_state')]
    public string $billingAddressState;

    /**
     *
     * @var string $billingAddressStreet1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address_street1')]
    public string $billingAddressStreet1;

    /**
     *
     * @var string $billingAddressZip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address_zip')]
    public string $billingAddressZip;

    /**
     * User's pickup address city.
     *
     * @var string $pickupAddressCity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pickup_address_city')]
    public string $pickupAddressCity;

    /**
     * User's pickup street 1.
     *
     * @var string $pickupAddressCountryIso2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pickup_address_country_iso2')]
    public string $pickupAddressCountryIso2;

    /**
     * User's pickup address state.
     *
     * @var string $pickupAddressState
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pickup_address_state')]
    public string $pickupAddressState;

    /**
     * User's pickup address street 1.
     *
     * @var string $pickupAddressStreet1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pickup_address_street1')]
    public string $pickupAddressStreet1;

    /**
     * User's pickup address zip code.
     *
     * @var string $pickupAddressZip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pickup_address_zip')]
    public string $pickupAddressZip;

    /**
     * Whether the user agrees to the UPS terms and conditions or not. Error 400 will be returned if passed in as false
     *
     * @var bool $upsAgreements
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ups_agreements')]
    public bool $upsAgreements;

    /**
     * Empty string acceptable for billing_address_street2
     *
     * @var ?string $billingAddressStreet2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address_street2')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingAddressStreet2 = null;

    /**
     * Company name. Full name is acceptable in this field if the user has no company name
     *
     * @var ?string $company
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('company')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $company = null;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     *
     * @var ?string $fullName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('full_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $fullName = null;

    /**
     * Needs to be a valid phone number and cannot be null
     *
     * @var ?string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phone = null;

    /**
     *
     * @var ?bool $pickupAddressSameAsBillingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pickup_address_same_as_billing_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $pickupAddressSameAsBillingAddress = null;

    /**
     * User's pickup street 2.
     *
     * @var ?string $pickupAddressStreet2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pickup_address_street2')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $pickupAddressStreet2 = null;

    /**
     * @param  string  $billingAddressCity
     * @param  string  $billingAddressCountryIso2
     * @param  string  $billingAddressState
     * @param  string  $billingAddressStreet1
     * @param  string  $billingAddressZip
     * @param  string  $pickupAddressCity
     * @param  string  $pickupAddressCountryIso2
     * @param  string  $pickupAddressState
     * @param  string  $pickupAddressStreet1
     * @param  string  $pickupAddressZip
     * @param  bool  $upsAgreements
     * @param  ?string  $billingAddressStreet2
     * @param  ?string  $company
     * @param  ?string  $email
     * @param  ?string  $fullName
     * @param  ?string  $phone
     * @param  ?bool  $pickupAddressSameAsBillingAddress
     * @param  ?string  $pickupAddressStreet2
     */
    public function __construct(string $billingAddressCity, string $billingAddressCountryIso2, string $billingAddressState, string $billingAddressStreet1, string $billingAddressZip, string $pickupAddressCity, string $pickupAddressCountryIso2, string $pickupAddressState, string $pickupAddressStreet1, string $pickupAddressZip, bool $upsAgreements, ?string $billingAddressStreet2 = null, ?string $company = null, ?string $email = null, ?string $fullName = null, ?string $phone = null, ?bool $pickupAddressSameAsBillingAddress = null, ?string $pickupAddressStreet2 = null)
    {
        $this->billingAddressCity = $billingAddressCity;
        $this->billingAddressCountryIso2 = $billingAddressCountryIso2;
        $this->billingAddressState = $billingAddressState;
        $this->billingAddressStreet1 = $billingAddressStreet1;
        $this->billingAddressZip = $billingAddressZip;
        $this->pickupAddressCity = $pickupAddressCity;
        $this->pickupAddressCountryIso2 = $pickupAddressCountryIso2;
        $this->pickupAddressState = $pickupAddressState;
        $this->pickupAddressStreet1 = $pickupAddressStreet1;
        $this->pickupAddressZip = $pickupAddressZip;
        $this->upsAgreements = $upsAgreements;
        $this->billingAddressStreet2 = $billingAddressStreet2;
        $this->company = $company;
        $this->email = $email;
        $this->fullName = $fullName;
        $this->phone = $phone;
        $this->pickupAddressSameAsBillingAddress = $pickupAddressSameAsBillingAddress;
        $this->pickupAddressStreet2 = $pickupAddressStreet2;
    }
}