<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class CarrierAccountDeutschePostCreateRequest
{
    /**
     *
     * @var \Shippo\API\Models\Components\CarrierAccountDeutschePostCreateRequestParameters $parameters
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parameters')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CarrierAccountDeutschePostCreateRequestParameters')]
    public CarrierAccountDeutschePostCreateRequestParameters $parameters;

    /**
     *
     * @var string $carrier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('carrier')]
    public string $carrier;

    /**
     * @param  string  $carrier
     * @param  \Shippo\API\Models\Components\CarrierAccountDeutschePostCreateRequestParameters  $parameters
     * @phpstan-pure
     */
    public function __construct(CarrierAccountDeutschePostCreateRequestParameters $parameters, string $carrier = 'deutsche_post')
    {
        $this->parameters = $parameters;
        $this->carrier = $carrier;
    }
}