<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class CarrierAccountCanadaPostCreateParameters
{
    /**
     * Whether or not the user agrees to Canada Post's terms. If passed in as false, request will fail with error 400
     *
     * @var bool $canadaPostTerms
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canada_post_terms')]
    public bool $canadaPostTerms;

    /**
     *
     * @var string $company
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('company')]
    public string $company;

    /**
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     *
     * @var string $fullName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('full_name')]
    public string $fullName;

    /**
     * Needs to be a valid phone number and cannot be null
     *
     * @var string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    public string $phone;

    /**
     * @param  bool  $canadaPostTerms
     * @param  string  $company
     * @param  string  $email
     * @param  string  $fullName
     * @param  string  $phone
     */
    public function __construct(bool $canadaPostTerms, string $company, string $email, string $fullName, string $phone)
    {
        $this->canadaPostTerms = $canadaPostTerms;
        $this->company = $company;
        $this->email = $email;
        $this->fullName = $fullName;
        $this->phone = $phone;
    }
}