<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/** CarrierParcelTemplateList - List of carrier parcel templates */
class CarrierParcelTemplateList
{
    /**
     * $results
     *
     * @var ?array<\Shippo\API\Models\Components\CarrierParcelTemplate> $results
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('results')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Shippo\API\Models\Components\CarrierParcelTemplate>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $results = null;

    /**
     * @param  ?array<\Shippo\API\Models\Components\CarrierParcelTemplate>  $results
     * @phpstan-pure
     */
    public function __construct(?array $results = null)
    {
        $this->results = $results;
    }
}