<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class CarrierAccountChronopostCreateRequest
{
    /**
     *
     * @var string $carrier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('carrier')]
    public string $carrier;

    /**
     *
     * @var CarrierAccountChronopostCreateRequestParameters $parameters
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parameters')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CarrierAccountChronopostCreateRequestParameters')]
    public CarrierAccountChronopostCreateRequestParameters $parameters;

    /**
     * @param  string  $carrier
     * @param  CarrierAccountChronopostCreateRequestParameters  $parameters
     */
    public function __construct(string $carrier, CarrierAccountChronopostCreateRequestParameters $parameters)
    {
        $this->carrier = $carrier;
        $this->parameters = $parameters;
    }
}