<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class CarrierAccountDHLExpressCreateRequest
{
    /**
     *
     * @var CarrierAccountDHLExpressCreateRequestParameters $parameters
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parameters')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CarrierAccountDHLExpressCreateRequestParameters')]
    public CarrierAccountDHLExpressCreateRequestParameters $parameters;

    /**
     *
     * @var string $carrier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('carrier')]
    public string $carrier;

    /**
     * @param  string  $carrier
     * @param  CarrierAccountDHLExpressCreateRequestParameters  $parameters
     * @phpstan-pure
     */
    public function __construct(CarrierAccountDHLExpressCreateRequestParameters $parameters, string $carrier = 'dhl_express')
    {
        $this->parameters = $parameters;
        $this->carrier = $carrier;
    }
}