<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class CarrierAccountUPSCreateRequest
{
    /**
     *
     * @var string $carrier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('carrier')]
    public string $carrier;

    /**
     *
     * @var ?CarrierAccountUPSCreateRequestParameters $parameters
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parameters')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CarrierAccountUPSCreateRequestParameters|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CarrierAccountUPSCreateRequestParameters $parameters = null;

    /**
     * @param  string  $carrier
     * @param  ?CarrierAccountUPSCreateRequestParameters  $parameters
     */
    public function __construct(string $carrier, ?CarrierAccountUPSCreateRequestParameters $parameters = null)
    {
        $this->carrier = $carrier;
        $this->parameters = $parameters;
    }
}