<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class CarrierAccountRoyalMailCreateRequest
{
    /**
     *
     * @var CarrierAccountRoyalMailCreateRequestParameters $parameters
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parameters')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CarrierAccountRoyalMailCreateRequestParameters')]
    public CarrierAccountRoyalMailCreateRequestParameters $parameters;

    /**
     *
     * @var string $carrier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('carrier')]
    public string $carrier;

    /**
     * @param  string  $carrier
     * @param  CarrierAccountRoyalMailCreateRequestParameters  $parameters
     * @phpstan-pure
     */
    public function __construct(CarrierAccountRoyalMailCreateRequestParameters $parameters, string $carrier = 'royal_mail')
    {
        $this->parameters = $parameters;
        $this->carrier = $carrier;
    }
}