<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class CarrierAccountCorreosCreateRequest
{
    /**
     *
     * @var string $carrier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('carrier')]
    public string $carrier;

    /**
     *
     * @var CarrierAccountCorreosCreateRequestParameters $parameters
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parameters')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CarrierAccountCorreosCreateRequestParameters')]
    public CarrierAccountCorreosCreateRequestParameters $parameters;

    /**
     * @param  string  $carrier
     * @param  CarrierAccountCorreosCreateRequestParameters  $parameters
     */
    public function __construct(string $carrier, CarrierAccountCorreosCreateRequestParameters $parameters)
    {
        $this->carrier = $carrier;
        $this->parameters = $parameters;
    }
}