<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/** Cod - Specify collection on delivery details (UPS only). */
class Cod
{
    /**
     * Amount to be collected.
     *
     * @var ?string $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $amount = null;

    /**
     * Currency for the amount to be collected. Currently only USD is supported for UPS.
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     * Secured funds include money orders, certified cheques and others (see 
     *
     * [UPS](https://www.ups.com/content/us/en/shipping/time/service/value_added/cod.html) for details). 
     * If no payment_method inputted the value defaults to "ANY".)
     *
     * @var ?\Shippo\API\Models\Components\PaymentMethod $paymentMethod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_method')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\PaymentMethod|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentMethod $paymentMethod = null;

    /**
     * @param  ?string  $amount
     * @param  ?string  $currency
     * @param  ?\Shippo\API\Models\Components\PaymentMethod  $paymentMethod
     * @phpstan-pure
     */
    public function __construct(?string $amount = null, ?string $currency = null, ?PaymentMethod $paymentMethod = null)
    {
        $this->amount = $amount;
        $this->currency = $currency;
        $this->paymentMethod = $paymentMethod;
    }
}