<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class ConnectExistingOwnAccountRequest
{
    /**
     *
     * @var string $accountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_id')]
    public string $accountId;

    /**
     *
     * @var ?bool $active
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $active = null;

    /**
     *
     * @var string $carrier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('carrier')]
    public string $carrier;

    /**
     *
     * @var ?string $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $metadata = null;

    /**
     *
     * @var array<string, mixed>|FedExConnectExistingOwnAccountParameters|UPSConnectExistingOwnAccountParameters $parameters
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parameters')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|\Shippo\API\Models\Components\FedExConnectExistingOwnAccountParameters|\Shippo\API\Models\Components\UPSConnectExistingOwnAccountParameters')]
    public array|FedExConnectExistingOwnAccountParameters|UPSConnectExistingOwnAccountParameters $parameters;

    /**
     *
     * @var ?bool $test
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('test')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $test = null;

    /**
     * @param  string  $accountId
     * @param  string  $carrier
     * @param  array<string, mixed>|FedExConnectExistingOwnAccountParameters|UPSConnectExistingOwnAccountParameters  $parameters
     * @param  ?bool  $active
     * @param  ?string  $metadata
     * @param  ?bool  $test
     */
    public function __construct(string $accountId, string $carrier, array|FedExConnectExistingOwnAccountParameters|UPSConnectExistingOwnAccountParameters $parameters, ?bool $active = null, ?string $metadata = null, ?bool $test = null)
    {
        $this->accountId = $accountId;
        $this->carrier = $carrier;
        $this->parameters = $parameters;
        $this->active = $active;
        $this->metadata = $metadata;
        $this->test = $test;
    }
}