<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/** CustomsDeclarationCreateRequestDutiesPayor - Specifies who will pay the duties for the shipment. Only accepted for FedEx shipments. */
class CustomsDeclarationCreateRequestDutiesPayor
{
    /**
     * Account number to be billed for duties.
     *
     * @var ?string $account
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $account = null;

    /**
     * Party to be billed for duties.
     *
     * @var ?CustomsDeclarationCreateRequestType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CustomsDeclarationCreateRequestType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CustomsDeclarationCreateRequestType $type = null;

    /**
     *
     * @var ?CustomsDeclarationCreateRequestAddress $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CustomsDeclarationCreateRequestAddress|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CustomsDeclarationCreateRequestAddress $address = null;

    /**
     * @param  ?string  $account
     * @param  ?CustomsDeclarationCreateRequestType  $type
     * @param  ?CustomsDeclarationCreateRequestAddress  $address
     * @phpstan-pure
     */
    public function __construct(?string $account = null, ?CustomsDeclarationCreateRequestType $type = null, ?CustomsDeclarationCreateRequestAddress $address = null)
    {
        $this->account = $account;
        $this->type = $type;
        $this->address = $address;
    }
}