<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * CustomsTaxIdentification - Tax identification that may be required to ship in certain countries. Typically used to assess duties on 
 *
 * goods that are crossing a border.
 */
class CustomsTaxIdentification
{
    /**
     * Tax identification number.
     *
     * @var ?string $number
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $number = null;

    /**
     * Type of tax identification.
     *
     * * `EIN` - Employer Identification Number, also known as a Federal Tax Identification Number.
     * * `VAT` - Value Added Tax identification number.
     * * `IOSS` - Import One-Stop Shop
     * * `ARN` - Australian Taxation Office Reference Number
     *
     * @var ?CustomsTaxIdentificationType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CustomsTaxIdentificationType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CustomsTaxIdentificationType $type = null;

    /**
     * @param  ?string  $number
     * @param  ?CustomsTaxIdentificationType  $type
     * @phpstan-pure
     */
    public function __construct(?string $number = null, ?CustomsTaxIdentificationType $type = null)
    {
        $this->number = $number;
        $this->type = $type;
    }
}