<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/** CustomsDeclarationDutiesPayor - Specifies who will pay the duties for the shipment. Only accepted for FedEx shipments. */
class CustomsDeclarationDutiesPayor
{
    /**
     * Account number to be billed for duties.
     *
     * @var ?string $account
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $account = null;

    /**
     * Party to be billed for duties.
     *
     * @var ?\Shippo\API\Models\Components\CustomsDeclarationType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CustomsDeclarationType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CustomsDeclarationType $type = null;

    /**
     *
     * @var ?\Shippo\API\Models\Components\CustomsDeclarationAddress $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CustomsDeclarationAddress|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CustomsDeclarationAddress $address = null;

    /**
     * @param  ?string  $account
     * @param  ?\Shippo\API\Models\Components\CustomsDeclarationType  $type
     * @param  ?\Shippo\API\Models\Components\CustomsDeclarationAddress  $address
     * @phpstan-pure
     */
    public function __construct(?string $account = null, ?CustomsDeclarationType $type = null, ?CustomsDeclarationAddress $address = null)
    {
        $this->account = $account;
        $this->type = $type;
        $this->address = $address;
    }
}