<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * The incoterm reference of the shipment. FCA is available for DHL Express and FedEx only. 
 *
 * eDAP is available for DPD UK only. DAP is available for DHL Express and DPD UK.
 * If expecting DAP for other carriers, please use DDU.
 * Allowed values available <a href="#tag/Customs-Declaration-Incoterm">here</a>
 */
enum CustomsDeclarationIncotermEnum: string
{
    case Ddp = 'DDP';
    case Ddu = 'DDU';
    case Fca = 'FCA';
    case Dap = 'DAP';
    case EDAP = 'eDAP';
}
