<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * DangerousGoodsObject - Container for specifying the presence of dangerous materials. This is specific to USPS, and if any contents
 *
 * are provided, only certain USPS service levels will be eligible. For more information, see our
 * [guide on hazardous or dangerous materials shipping](https://docs.goshippo.com/docs/shipments/hazmat/).
 */
class DangerousGoodsObject
{
    /**
     * Indicates if the shipment contains dangerous goods.
     *
     * @var ?bool $contains
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contains')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $contains = null;

    /**
     * Container for specifying the presence of biological material.
     *
     * @var ?\Shippo\API\Models\Components\DangerousGoodsBiologicalMaterial $biologicalMaterial
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('biological_material')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\DangerousGoodsBiologicalMaterial|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DangerousGoodsBiologicalMaterial $biologicalMaterial = null;

    /**
     * Container for specifying the presence of lithium batteries.
     *
     * @var ?\Shippo\API\Models\Components\DangerousGoodsLithiumBatteries $lithiumBatteries
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lithium_batteries')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\DangerousGoodsLithiumBatteries|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DangerousGoodsLithiumBatteries $lithiumBatteries = null;

    /**
     * @param  ?bool  $contains
     * @param  ?\Shippo\API\Models\Components\DangerousGoodsBiologicalMaterial  $biologicalMaterial
     * @param  ?\Shippo\API\Models\Components\DangerousGoodsLithiumBatteries  $lithiumBatteries
     * @phpstan-pure
     */
    public function __construct(?bool $contains = null, ?DangerousGoodsBiologicalMaterial $biologicalMaterial = null, ?DangerousGoodsLithiumBatteries $lithiumBatteries = null)
    {
        $this->contains = $contains;
        $this->biologicalMaterial = $biologicalMaterial;
        $this->lithiumBatteries = $lithiumBatteries;
    }
}