<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/** The measure unit used for length, width and height. */
enum DistanceUnitEnum: string
{
    case Cm = 'cm';
    case In = 'in';
    case Ft = 'ft';
    case M = 'm';
    case Mm = 'mm';
    case Yd = 'yd';
}
