<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class FedExConnectExistingOwnAccountParameters
{
    /**
     * First name of the account holder
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    public string $firstName;

    /**
     * Last name of the account holder
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    public string $lastName;

    /**
     * Phone number of the account holder
     *
     * @var string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone_number')]
    public string $phoneNumber;

    /**
     * Street address of the account holder
     *
     * @var string $fromAddressSt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from_address_st')]
    public string $fromAddressSt;

    /**
     * City of the account holder
     *
     * @var string $fromAddressCity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from_address_city')]
    public string $fromAddressCity;

    /**
     * State of the account holder
     *
     * @var string $fromAddressState
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from_address_state')]
    public string $fromAddressState;

    /**
     * Zip code of the account holder
     *
     * @var string $fromAddressZip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from_address_zip')]
    public string $fromAddressZip;

    /**
     * Country of the account holder
     *
     * @var string $fromAddressCountryIso2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from_address_country_iso2')]
    public string $fromAddressCountryIso2;

    /**
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  string  $phoneNumber
     * @param  string  $fromAddressSt
     * @param  string  $fromAddressCity
     * @param  string  $fromAddressState
     * @param  string  $fromAddressZip
     * @param  string  $fromAddressCountryIso2
     */
    public function __construct(string $firstName, string $lastName, string $phoneNumber, string $fromAddressSt, string $fromAddressCity, string $fromAddressState, string $fromAddressZip, string $fromAddressCountryIso2)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->phoneNumber = $phoneNumber;
        $this->fromAddressSt = $fromAddressSt;
        $this->fromAddressCity = $fromAddressCity;
        $this->fromAddressState = $fromAddressState;
        $this->fromAddressZip = $fromAddressZip;
        $this->fromAddressCountryIso2 = $fromAddressCountryIso2;
    }
}