<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/** InvoiceNumber - Specify the invoice number field on the label (FedEx and UPS only). */
class InvoiceNumber
{
    /**
     * Custom prefix for invoice number field (ZPL labels only). Up to 11 characters, including trailing 
     *
     * spaces. Empty string indicates removal of default prefix. To use the default prefix, do not include
     * this property.
     *
     * @var ?string $prefix
     */
    #[\JMS\Serializer\Annotation\SerializedName('prefix')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $prefix = null;

    /**
     * Optional text to be printed on the shipping label for invoice number. Up to 40 characters. If 
     *
     * provided, this will be used on the label instead of shipment.customs_declaration.invoice.
     *
     * @var ?string $value
     */
    #[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $value = null;

    /**
     * Order UPS reference fields are printed on ZPL labels. For UPS shipments, if you choose to set `ref_sort` for one reference, you must set `ref_sort` for all other supported UPS references using unique integers.
     *
     * @var ?int $refSort
     */
    #[\JMS\Serializer\Annotation\SerializedName('ref_sort')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $refSort = null;

    public function __construct()
    {
        $this->prefix = null;
        $this->value = null;
        $this->refSort = null;
    }
}