<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


enum LabelFileType: string
{
    case Png = 'PNG';
    case PNG23x75 = 'PNG_2.3x7.5';
    case Pdf = 'PDF';
    case PDF23x75 = 'PDF_2.3x7.5';
    case PDF4x6 = 'PDF_4x6';
    case PDF4x8 = 'PDF_4x8';
    case PdfA4 = 'PDF_A4';
    case PdfA6 = 'PDF_A6';
    case Zplii = 'ZPLII';
}
