<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class LineItem
{
    /**
     * Currency of the <code>total_price</code> amount.
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     * Country the item was manufactured in. In the Shippo dashboard, this value will be used ot pre-fill the customs declaration when creating a label for this order.
     *
     * @var ?string $manufactureCountry
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('manufacture_country')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $manufactureCountry = null;

    /**
     * The date and time this item needs to be delivered by, i.e. by when the carrier delivers it to the buyer. 
     *
     * This value is used by some platforms such as eBay to measure a seller's shipping time and performance. 
     * It will be displayed in the Shippo dashboard.
     *
     * @var ?\DateTime $maxDeliveryTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('max_delivery_time')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $maxDeliveryTime = null;

    /**
     * The date and time this item needs to be fulfilled by, i.e. by when the shipping label needs to be 
     *
     * created and handed over to the carrier. This value is used by some platforms such as eBay to measure 
     * a seller's handling time and performance. It will be displayed in the Shippo dashboard.
     *
     * @var ?\DateTime $maxShipTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('max_ship_time')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $maxShipTime = null;

    /**
     * The quantity of this item in this order.
     *
     * @var ?int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $quantity = null;

    /**
     * The stock keeping unit value of this item.
     *
     * @var ?string $sku
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sku')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sku = null;

    /**
     * Title of the line item.
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * Total price paid by the buyer for this item (or these items, if quantity > 1).
     *
     * @var ?string $totalPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_price')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $totalPrice = null;

    /**
     * A variant is a specific variation of an item (e.g. `size M` or `color blue`). 
     *
     * Variants might be exposed as a separate resource in the future too. 
     * Currently the variant title is a free text field describing the variant.
     *
     * @var ?string $variantTitle
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variant_title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $variantTitle = null;

    /**
     * Total weight of this/these item(s). Instead of specifying the weight of all items, 
     *
     * you can also set the <code>total_weight</code> value of the order object.
     *
     * @var ?string $weight
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('weight')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $weight = null;

    /**
     * The unit used for weight.
     *
     * @var ?WeightUnitEnum $weightUnit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('weight_unit')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\WeightUnitEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?WeightUnitEnum $weightUnit = null;

    /**
     * Unique identifier of the line item object.
     *
     * @var ?string $objectId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $objectId = null;

    /**
     * @param  ?string  $currency
     * @param  ?string  $manufactureCountry
     * @param  ?\DateTime  $maxDeliveryTime
     * @param  ?\DateTime  $maxShipTime
     * @param  ?int  $quantity
     * @param  ?string  $sku
     * @param  ?string  $title
     * @param  ?string  $totalPrice
     * @param  ?string  $variantTitle
     * @param  ?string  $weight
     * @param  ?WeightUnitEnum  $weightUnit
     * @param  ?string  $objectId
     * @phpstan-pure
     */
    public function __construct(?string $currency = null, ?string $manufactureCountry = null, ?\DateTime $maxDeliveryTime = null, ?\DateTime $maxShipTime = null, ?int $quantity = null, ?string $sku = null, ?string $title = null, ?string $totalPrice = null, ?string $variantTitle = null, ?string $weight = null, ?WeightUnitEnum $weightUnit = null, ?string $objectId = null)
    {
        $this->currency = $currency;
        $this->manufactureCountry = $manufactureCountry;
        $this->maxDeliveryTime = $maxDeliveryTime;
        $this->maxShipTime = $maxShipTime;
        $this->quantity = $quantity;
        $this->sku = $sku;
        $this->title = $title;
        $this->totalPrice = $totalPrice;
        $this->variantTitle = $variantTitle;
        $this->weight = $weight;
        $this->weightUnit = $weightUnit;
        $this->objectId = $objectId;
    }
}