<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class Manifest
{
    /**
     * ID of carrier account
     *
     * @var string $carrierAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('carrier_account')]
    public string $carrierAccount;

    /**
     * All shipments to be submitted on this day will be closed out. 
     *
     * Must be in the format `2014-01-18T00:35:03.463Z` (ISO 8601 date).
     *
     * @var string $shipmentDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('shipment_date')]
    public string $shipmentDate;

    /**
     * ID of the Address object that should be used as pickup address for the scan form. 
     *
     * The USPS will validate this address before creating the scan form.
     *
     * @var string $addressFrom
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address_from')]
    public string $addressFrom;

    /**
     * An array containing the URLs to all returned manifest documents.
     *
     * @var array<string> $documents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('documents')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $documents;

    /**
     * Date and time of object creation.
     *
     * @var \DateTime $objectCreated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_created')]
    public \DateTime $objectCreated;

    /**
     * Unique identifier of the given object.
     *
     * @var string $objectId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_id')]
    public string $objectId;

    /**
     * Username of the user who created the object.
     *
     * @var string $objectOwner
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_owner')]
    public string $objectOwner;

    /**
     * Date and time of last object update.
     *
     * @var \DateTime $objectUpdated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_updated')]
    public \DateTime $objectUpdated;

    /**
     * Indicates the status of the manifest.
     *
     * @var ManifestStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\ManifestStatus')]
    public ManifestStatus $status;

    /**
     * IDs transactions to use. If you set this to null or not send this parameter, 
     *
     * Shippo will automatically assign all applicable transactions.
     *
     * @var ?array<string> $transactions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transactions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $transactions = null;

    /**
     * An array of codes and messages describing the error that occurred if any.
     *
     * @var ?array<string> $errors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('errors')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $errors = null;

    /**
     * @param  string  $carrierAccount
     * @param  string  $shipmentDate
     * @param  string  $addressFrom
     * @param  array<string>  $documents
     * @param  \DateTime  $objectCreated
     * @param  string  $objectId
     * @param  string  $objectOwner
     * @param  \DateTime  $objectUpdated
     * @param  ManifestStatus  $status
     * @param  ?array<string>  $transactions
     * @param  ?array<string>  $errors
     */
    public function __construct(string $carrierAccount, string $shipmentDate, string $addressFrom, array $documents, \DateTime $objectCreated, string $objectId, string $objectOwner, \DateTime $objectUpdated, ManifestStatus $status, ?array $transactions = null, ?array $errors = null)
    {
        $this->carrierAccount = $carrierAccount;
        $this->shipmentDate = $shipmentDate;
        $this->addressFrom = $addressFrom;
        $this->documents = $documents;
        $this->objectCreated = $objectCreated;
        $this->objectId = $objectId;
        $this->objectOwner = $objectOwner;
        $this->objectUpdated = $objectUpdated;
        $this->status = $status;
        $this->transactions = $transactions;
        $this->errors = $errors;
    }
}