<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class Order
{
    /**
     * **Required if total_price is provided**<br>
     *
     * Currency of the <code>total_price</code> and <code>total_tax</code> amounts.
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     * Custom buyer- or seller-provided notes about the order.
     *
     * @var ?string $notes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('notes')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $notes = null;

    /**
     * An alphanumeric identifier for the order used by the seller/buyer. This identifier doesn't need to be unique.
     *
     * @var ?string $orderNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('order_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $orderNumber = null;

    /**
     * Current state of the order. See the <a href="https://docs.goshippo.com/docs/orders/orders/">orders tutorial</a> 
     *
     * for the logic of how the status is handled.
     *
     * @var ?OrderStatusEnum $orderStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('order_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\OrderStatusEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrderStatusEnum $orderStatus = null;

    /**
     * Date and time when the order was placed. This datetime can be different from the datetime of the order object creation on Shippo.
     *
     * @var string $placedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('placed_at')]
    public string $placedAt;

    /**
     * Amount paid by the buyer for shipping. This amount can be different from the price the seller will actually pay for shipping.
     *
     * @var ?string $shippingCost
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('shipping_cost')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $shippingCost = null;

    /**
     * **Required if shipping_cost is provided**<br>
     *
     * Currency of the <code>shipping_cost</code> amount.
     *
     * @var ?string $shippingCostCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('shipping_cost_currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $shippingCostCurrency = null;

    /**
     * Shipping method (carrier + service or other free text description) chosen by the buyer. 
     *
     * This value can be different from the shipping method the seller will actually choose.
     *
     * @var ?string $shippingMethod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('shipping_method')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $shippingMethod = null;

    /**
     *
     * @var ?string $subtotalPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtotal_price')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $subtotalPrice = null;

    /**
     * Total amount paid by the buyer for this order.
     *
     * @var ?string $totalPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_price')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $totalPrice = null;

    /**
     * Total tax amount paid by the buyer for this order.
     *
     * @var ?string $totalTax
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_tax')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $totalTax = null;

    /**
     * Total weight of the order.
     *
     * @var ?string $weight
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('weight')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $weight = null;

    /**
     * The unit used for weight.
     *
     * @var ?WeightUnitEnum $weightUnit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('weight_unit')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\WeightUnitEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?WeightUnitEnum $weightUnit = null;

    /**
     * <a href="#tag/Addresses">Address</a> object of the sender / seller. Will be returned expanded by default.
     *
     * @var ?Address $fromAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\Address|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Address $fromAddress = null;

    /**
     * <a href="#tag/Addresses">Address</a> object of the recipient / buyer. Will be returned expanded by default.
     *
     * @var Address $toAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('to_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\Address')]
    public Address $toAddress;

    /**
     * Array of <a href="#section/Line-Item">line item</a> objects representing the items in this order. 
     *
     * All objects will be returned expanded by default.
     *
     * @var ?array<LineItem> $lineItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('line_items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Shippo\API\Models\Components\LineItem>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $lineItems = null;

    /**
     * Unique identifier of the order object.
     *
     * @var ?string $objectId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $objectId = null;

    /**
     * Username of the user who created the object.
     *
     * @var ?string $objectOwner
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_owner')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $objectOwner = null;

    /**
     * Platform the order was created on and, if applicable, imported from. 
     *
     * Orders created via the Shippo API or dashboard will have the value "Shippo".
     *
     * @var ?OrderShopAppEnum $shopApp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('shop_app')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\OrderShopAppEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrderShopAppEnum $shopApp = null;

    /**
     * Array of <a href="#tag/Transactions">transaction</a> objects representing all shipping labels purchased for this order.
     *
     * All objects are returned expanded with a limited number of fields by default.
     *
     * @var ?array<string> $transactions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transactions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $transactions = null;

    /**
     * @param  string  $placedAt
     * @param  Address  $toAddress
     * @param  ?string  $currency
     * @param  ?string  $notes
     * @param  ?string  $orderNumber
     * @param  ?OrderStatusEnum  $orderStatus
     * @param  ?string  $shippingCost
     * @param  ?string  $shippingCostCurrency
     * @param  ?string  $shippingMethod
     * @param  ?string  $subtotalPrice
     * @param  ?string  $totalPrice
     * @param  ?string  $totalTax
     * @param  ?string  $weight
     * @param  ?WeightUnitEnum  $weightUnit
     * @param  ?Address  $fromAddress
     * @param  ?array<LineItem>  $lineItems
     * @param  ?string  $objectId
     * @param  ?string  $objectOwner
     * @param  ?OrderShopAppEnum  $shopApp
     * @param  ?array<string>  $transactions
     */
    public function __construct(string $placedAt, Address $toAddress, ?string $currency = null, ?string $notes = null, ?string $orderNumber = null, ?OrderStatusEnum $orderStatus = null, ?string $shippingCost = null, ?string $shippingCostCurrency = null, ?string $shippingMethod = null, ?string $subtotalPrice = null, ?string $totalPrice = null, ?string $totalTax = null, ?string $weight = null, ?WeightUnitEnum $weightUnit = null, ?Address $fromAddress = null, ?array $lineItems = null, ?string $objectId = null, ?string $objectOwner = null, ?OrderShopAppEnum $shopApp = null, ?array $transactions = null)
    {
        $this->placedAt = $placedAt;
        $this->toAddress = $toAddress;
        $this->currency = $currency;
        $this->notes = $notes;
        $this->orderNumber = $orderNumber;
        $this->orderStatus = $orderStatus;
        $this->shippingCost = $shippingCost;
        $this->shippingCostCurrency = $shippingCostCurrency;
        $this->shippingMethod = $shippingMethod;
        $this->subtotalPrice = $subtotalPrice;
        $this->totalPrice = $totalPrice;
        $this->totalTax = $totalTax;
        $this->weight = $weight;
        $this->weightUnit = $weightUnit;
        $this->fromAddress = $fromAddress;
        $this->lineItems = $lineItems;
        $this->objectId = $objectId;
        $this->objectOwner = $objectOwner;
        $this->shopApp = $shopApp;
        $this->transactions = $transactions;
    }
}