<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * |Token | Name | Dimensions|
 *
 * |:---|:---|:---|
 * | Fastway_Australia_Satchel_A2 | Satchel A2 | 594.00 x 420.00 x 48.00 mm|
 * | Fastway_Australia_Satchel_A3 | Satchel A3 | 420.00 x 297.00 x 64.00 mm|
 * | Fastway_Australia_Satchel_A4 | Satchel A4 | 297.00 x 210.00 x 64.00 mm|
 * | Fastway_Australia_Satchel_A5 | Satchel A5 | 210.00 x 148.00 x 64.00 mm|
 *
 */
enum ParcelTemplateAramexAustraliaEnum: string
{
    case FastwayAustraliaSatchelA2 = 'Fastway_Australia_Satchel_A2';
    case FastwayAustraliaSatchelA3 = 'Fastway_Australia_Satchel_A3';
    case FastwayAustraliaSatchelA4 = 'Fastway_Australia_Satchel_A4';
    case FastwayAustraliaSatchelA5 = 'Fastway_Australia_Satchel_A5';
}
