<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * |Token | Name | Dimensions|
 *
 * |:---|:---|:---|
 * | UPS_Box_10kg | Box 10kg | 410.00 x 335.00 x 265.00 mm|
 * | UPS_Box_25kg | Box 25kg | 484.00 x 433.00 x 350.00 mm|
 * | UPS_Express_Box | Express Box | 460.00 x 315.00 x 95.00 mm|
 * | UPS_Express_Box_Large | Express Box Large | 18.00 x 13.00 x 3.00 in|
 * | UPS_Express_Box_Medium | Express Box Medium | 15.00 x 11.00 x 3.00 in|
 * | UPS_Express_Box_Small | Express Box Small | 13.00 x 11.00 x 2.00 in|
 * | UPS_Express_Envelope | Express Envelope | 12.50 x 9.50 x 2.00 in|
 * | UPS_Express_Hard_Pak | Express Hard Pak | 14.75 x 11.50 x 2.00 in|
 * | UPS_Express_Legal_Envelope | Express Legal Envelope | 15.00 x 9.50 x 2.00 in|
 * | UPS_Express_Pak | Express Pak | 16.00 x 12.75 x 2.00 in|
 * | UPS_Express_Tube | Express Tube | 970.00 x 190.00 x 165.00 mm|
 * | UPS_Laboratory_Pak | Laboratory Pak | 17.25 x 12.75 x 2.00 in|
 * | UPS_MI_BPM | BPM (Mail Innovations - Domestic &amp; International) | 0.00 x 0.00 x 0.00 in|
 * | UPS_MI_BPM_Flat | BPM Flat (Mail Innovations - Domestic &amp; International) | 0.00 x 0.00 x 0.00 in|
 * | UPS_MI_BPM_Parcel | BPM Parcel (Mail Innovations - Domestic &amp; International) | 0.00 x 0.00 x 0.00 in|
 * | UPS_MI_First_Class | First Class (Mail Innovations - Domestic only) | 0.00 x 0.00 x 0.00 in|
 * | UPS_MI_Flat | Flat (Mail Innovations - Domestic only) | 0.00 x 0.00 x 0.00 in|
 * | UPS_MI_Irregular | Irregular (Mail Innovations - Domestic only) | 0.00 x 0.00 x 0.00 in|
 * | UPS_MI_Machinable | Machinable (Mail Innovations - Domestic only) | 0.00 x 0.00 x 0.00 in|
 * | UPS_MI_MEDIA_MAIL | Media Mail (Mail Innovations - Domestic only) | 0.00 x 0.00 x 0.00 in|
 * | UPS_MI_Parcel_Post | Parcel Post (Mail Innovations - Domestic only) | 0.00 x 0.00 x 0.00 in|
 * | UPS_MI_Priority | Priority (Mail Innovations - Domestic only) | 0.00 x 0.00 x 0.00 in|
 * | UPS_MI_Standard_Flat | Standard Flat (Mail Innovations - Domestic only) | 0.00 x 0.00 x 0.00 in|
 * | UPS_Pad_Pak | Pad Pak | 14.75 x 11.00 x 2.00 in|
 * | UPS_Pallet | Pallet | 120.00 x 80.00 x 200.00 cm|
 *
 */
enum ParcelTemplateUPSEnum: string
{
    case UPSBox10kg = 'UPS_Box_10kg';
    case UPSBox25kg = 'UPS_Box_25kg';
    case UPSExpressBox = 'UPS_Express_Box';
    case UPSExpressBoxLarge = 'UPS_Express_Box_Large';
    case UPSExpressBoxMedium = 'UPS_Express_Box_Medium';
    case UPSExpressBoxSmall = 'UPS_Express_Box_Small';
    case UPSExpressEnvelope = 'UPS_Express_Envelope';
    case UPSExpressHardPak = 'UPS_Express_Hard_Pak';
    case UPSExpressLegalEnvelope = 'UPS_Express_Legal_Envelope';
    case UPSExpressPak = 'UPS_Express_Pak';
    case UPSExpressTube = 'UPS_Express_Tube';
    case UPSLaboratoryPak = 'UPS_Laboratory_Pak';
    case UpsMiBpm = 'UPS_MI_BPM';
    case UPSMIBPMFlat = 'UPS_MI_BPM_Flat';
    case UPSMIBPMParcel = 'UPS_MI_BPM_Parcel';
    case UPSMIFirstClass = 'UPS_MI_First_Class';
    case UPSMIFlat = 'UPS_MI_Flat';
    case UPSMIIrregular = 'UPS_MI_Irregular';
    case UPSMIMachinable = 'UPS_MI_Machinable';
    case UpsMiMediaMail = 'UPS_MI_MEDIA_MAIL';
    case UPSMIParcelPost = 'UPS_MI_Parcel_Post';
    case UPSMIPriority = 'UPS_MI_Priority';
    case UPSMIStandardFlat = 'UPS_MI_Standard_Flat';
    case UPSPadPak = 'UPS_Pad_Pak';
    case UPSPallet = 'UPS_Pallet';
}
