<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * ParentServicelevel - Used for some Service Levels to link to the more "generic" version of this Service Level - for example, 
 *
 * if this Service Level is a variation specific to shipments to Europe("ups_saver_eu"), the "parent" is 
 * the fully generic version ("ups_saver"). Helpful when displaying Service Levels to users. Has the same 
 * structure of the servicelevel - "name", "token", "terms", and "extended_token", or it is otherwise null.
 */
class ParentServicelevel
{
    /**
     * Name of the Rate's servicelevel, e.g. `International Priority` or `Standard Post`. 
     *
     * A servicelevel commonly defines the transit time of a Shipment (e.g., Express vs. Standard), along with other properties. 
     * These names vary depending on the provider.
     *
     * @var ?string $name
     */
    #[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;

    /**
     * Further clarification of the service.
     *
     * @var ?string $terms
     */
    #[\JMS\Serializer\Annotation\SerializedName('terms')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $terms = null;

    /**
     * Token of the Rate's servicelevel, e.g. `usps_priority` or `fedex_ground`. 
     *
     * See <a href="#tag/Service-Levels">servicelevels</a>.
     *
     * @var ?string $token
     */
    #[\JMS\Serializer\Annotation\SerializedName('token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $token = null;

    /**
     * Unique, extended version of the Service Level "token". 
     *
     * Guaranteed to be unique across all Service Levels, and may help offer insight into the specific Service Level it describes.
     *
     * @var ?string $extendedToken
     */
    #[\JMS\Serializer\Annotation\SerializedName('extended_token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $extendedToken = null;

    public function __construct()
    {
        $this->name = null;
        $this->terms = null;
        $this->token = null;
        $this->extendedToken = null;
    }
}