<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class Pickup
{
    /**
     * The object ID of your USPS or DHL Express carrier account. 
     *
     * You can retrieve this from your Rate requests or our <a href="#tag/Carrier-Accounts/">Carrier Accounts</a> endpoint.
     *
     * @var string $carrierAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('carrier_account')]
    public string $carrierAccount;

    /**
     * Location where the parcel(s) will be picked up.
     *
     * @var Location $location
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('location')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\Location')]
    public Location $location;

    /**
     * A string of up to 100 characters that can be filled with any additional information you 
     *
     * want to attach to the object.
     *
     * @var ?string $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $metadata = null;

    /**
     * The latest that you requested your parcels to be available for pickup. 
     *
     * Expressed in the timezone specified in the response.
     *
     * @var \DateTime $requestedEndTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('requested_end_time')]
    public \DateTime $requestedEndTime;

    /**
     * The earliest that you requested your parcels to be ready for pickup. 
     *
     * Expressed in the timezone specified in the response.
     *
     * @var \DateTime $requestedStartTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('requested_start_time')]
    public \DateTime $requestedStartTime;

    /**
     * The transaction(s) object ID(s) for the parcel(s) that need to be picked up.
     *
     * @var array<string> $transactions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transactions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $transactions;

    /**
     * Date and time of Pickup creation.
     *
     * @var ?\DateTime $objectCreated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_created')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $objectCreated = null;

    /**
     * Unique identifier of the given Pickup object.
     *
     * @var ?string $objectId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $objectId = null;

    /**
     * Date and time of last Pickup update.
     *
     * @var ?\DateTime $objectUpdated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_updated')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $objectUpdated = null;

    /**
     * The earliest that your parcels will be ready for pickup, confirmed by the carrier. 
     *
     * Expressed in the timezone specified in the response.
     *
     * @var ?string $confirmedStartTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('confirmed_start_time')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $confirmedStartTime = null;

    /**
     * The latest that your parcels will be available for pickup, confirmed by the carrier. 
     *
     * Expressed in the timezone specified in the response.
     *
     * @var ?string $confirmedEndTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('confirmed_end_time')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $confirmedEndTime = null;

    /**
     * The latest time to cancel a pickup. Expressed in the timezone specified in the response. 
     *
     * To cancel a pickup, you will need to contact the carrier directly. 
     * The ability to cancel a pickup through Shippo may be released in future iterations.
     *
     * @var ?string $cancelByTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cancel_by_time')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $cancelByTime = null;

    /**
     * Indicates the status of the pickup.
     *
     * @var ?PickupStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\PickupStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PickupStatus $status = null;

    /**
     * Pickup's confirmation code returned by the carrier. 
     *
     * To edit or cancel a pickup, you will need to contact USPS or DHL Express directly and provide your `confirmation_code`.
     *
     * @var ?string $confirmationCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('confirmation_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $confirmationCode = null;

    /**
     * The pickup time windows will be in the time zone specified here, not UTC.
     *
     * @var ?string $timezone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timezone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $timezone = null;

    /**
     * An array containing strings of any messages generated during validation.
     *
     * @var ?array<string> $messages
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('messages')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $messages = null;

    /**
     * Indicates whether the object has been created in test mode.
     *
     * @var ?bool $isTest
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_test')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isTest = null;

    /**
     * @param  string  $carrierAccount
     * @param  Location  $location
     * @param  \DateTime  $requestedEndTime
     * @param  \DateTime  $requestedStartTime
     * @param  array<string>  $transactions
     * @param  ?string  $metadata
     * @param  ?\DateTime  $objectCreated
     * @param  ?string  $objectId
     * @param  ?\DateTime  $objectUpdated
     * @param  ?string  $confirmedStartTime
     * @param  ?string  $confirmedEndTime
     * @param  ?string  $cancelByTime
     * @param  ?PickupStatus  $status
     * @param  ?string  $confirmationCode
     * @param  ?string  $timezone
     * @param  ?array<string>  $messages
     * @param  ?bool  $isTest
     */
    public function __construct(string $carrierAccount, Location $location, \DateTime $requestedEndTime, \DateTime $requestedStartTime, array $transactions, ?string $metadata = null, ?\DateTime $objectCreated = null, ?string $objectId = null, ?\DateTime $objectUpdated = null, ?string $confirmedStartTime = null, ?string $confirmedEndTime = null, ?string $cancelByTime = null, ?PickupStatus $status = null, ?string $confirmationCode = null, ?string $timezone = null, ?array $messages = null, ?bool $isTest = null)
    {
        $this->carrierAccount = $carrierAccount;
        $this->location = $location;
        $this->requestedEndTime = $requestedEndTime;
        $this->requestedStartTime = $requestedStartTime;
        $this->transactions = $transactions;
        $this->metadata = $metadata;
        $this->objectCreated = $objectCreated;
        $this->objectId = $objectId;
        $this->objectUpdated = $objectUpdated;
        $this->confirmedStartTime = $confirmedStartTime;
        $this->confirmedEndTime = $confirmedEndTime;
        $this->cancelByTime = $cancelByTime;
        $this->status = $status;
        $this->confirmationCode = $confirmationCode;
        $this->timezone = $timezone;
        $this->messages = $messages;
        $this->isTest = $isTest;
    }
}