<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/** Policy to indicate if the Account needs multi-factor verification. */
enum Policy: string
{
    case Required = 'required';
    case NotRequired = 'not-required';
}
