<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class ServiceGroupAccountAndServiceLevel
{
    /**
     * ID of a Carrier Account object
     *
     * @var ?string $accountObjectId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_object_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $accountObjectId = null;

    /**
     * Service level token, e.g. `usps_priority` or `fedex_ground`.<br>
     *
     * See <a href="#tag/Service-Levels">Service Levels</a>.
     *
     * @var ?string $serviceLevelToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('service_level_token')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $serviceLevelToken = null;

    /**
     * @param  ?string  $accountObjectId
     * @param  ?string  $serviceLevelToken
     * @phpstan-pure
     */
    public function __construct(?string $accountObjectId = null, ?string $serviceLevelToken = null)
    {
        $this->accountObjectId = $accountObjectId;
        $this->serviceLevelToken = $serviceLevelToken;
    }
}