<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * |Token | Service name|
 *
 * |:---|:---|
 * | gls_us_cps | GSO Ground|
 * | gls_us_eps | Early Priority Overnight|
 * | gls_us_ess | Early Saturday Delivery|
 * | gls_us_nps | Noon Priority Overnight|
 * | gls_us_pds | Priority Overnight|
 * | gls_us_sds | Saturday Delivery|
 *
 */
enum ServiceLevelGLSUSEnum: string
{
    case GlsUsCps = 'gls_us_cps';
    case GlsUsEps = 'gls_us_eps';
    case GlsUsEss = 'gls_us_ess';
    case GlsUsNps = 'gls_us_nps';
    case GlsUsPds = 'gls_us_pds';
    case GlsUsSds = 'gls_us_sds';
}
