<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * |Token | Service name|
 *
 * |:---|:---|
 * | lso_ground | Ground|
 * | lso_economy_next_day | Economy Next Day|
 * | lso_saturday_delivery | Saturday Delivery|
 * | lso_2nd_day | 2nd Day|
 * | lso_priority_next_day | Priority Next Day|
 * | lso_early_overnight | Early Overnight|
 *
 */
enum ServiceLevelLSOEnum: string
{
    case LsoGround = 'lso_ground';
    case LsoEconomyNextDay = 'lso_economy_next_day';
    case LsoSaturdayDelivery = 'lso_saturday_delivery';
    case Lso2ndDay = 'lso_2nd_day';
    case LsoPriorityNextDay = 'lso_priority_next_day';
    case LsoEarlyOvernight = 'lso_early_overnight';
}
