<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * |Token | Service name|
 *
 * |:---|:---|
 * | globegistics_priority_mail_express_international | Globegistics Priority Mail Express International|
 * | globegistics_priority_mail_international | Globegistics Priority Mail International|
 * | globegistics_priority_mail_express_international_pds | Globegistics Priority Mail Express International PreSort Drop Ship|
 * | globegistics_priority_mail_international_pds | Globegistics Priority Mail International PreSort Drop Ship|
 * | globegistics_epacket | Globegistics ePacket|
 * | globegistics_ecom_tracked_ddp | Globegistics eCom Tracked DDP|
 * | globegistics_ecom_packet_ddp | Globegistics eCom Packet DDP|
 * | globegistics_ecom_priority_mail_international_ddp | Globegistics eCom Priority Mail International DDP|
 * | globegistics_ecom_priority_mail_express_international_ddp | Globegistics eCom Priority Mail Express International DDP|
 * | globegistics_ecom_extra | Globegistics eCom Extra|
 * | globegistics_ecom_international_priority_airmail | Globegistics eCom International Priority Airmail|
 * | globegistics_ecom_international_surface_airlift | Globegistics eCom International Surface Air Lift|
 *
 */
enum ServiceLevelGlobegisticsEnum: string
{
    case GlobegisticsPriorityMailExpressInternational = 'globegistics_priority_mail_express_international';
    case GlobegisticsPriorityMailInternational = 'globegistics_priority_mail_international';
    case GlobegisticsPriorityMailExpressInternationalPds = 'globegistics_priority_mail_express_international_pds';
    case GlobegisticsPriorityMailInternationalPds = 'globegistics_priority_mail_international_pds';
    case GlobegisticsEpacket = 'globegistics_epacket';
    case GlobegisticsEcomTrackedDdp = 'globegistics_ecom_tracked_ddp';
    case GlobegisticsEcomPacketDdp = 'globegistics_ecom_packet_ddp';
    case GlobegisticsEcomPriorityMailInternationalDdp = 'globegistics_ecom_priority_mail_international_ddp';
    case GlobegisticsEcomPriorityMailExpressInternationalDdp = 'globegistics_ecom_priority_mail_express_international_ddp';
    case GlobegisticsEcomExtra = 'globegistics_ecom_extra';
    case GlobegisticsEcomInternationalPriorityAirmail = 'globegistics_ecom_international_priority_airmail';
    case GlobegisticsEcomInternationalSurfaceAirlift = 'globegistics_ecom_international_surface_airlift';
}
