<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * |Token | Service name|
 *
 * |:---|:---|
 * | dhl_germany_europaket | DHL Germany Europaket|
 * | dhl_germany_paket | DHL Germany Paket|
 * | dhl_germany_paket_connect | DHL Germany Paket Connect|
 * | dhl_germany_paket_international | DHL Germany Paket International|
 * | dhl_germany_paket_priority | DHL Germany Paket Priority|
 * | dhl_germany_paket_sameday | DHL Germany Paket Sameday|
 *
 */
enum ServiceLevelDHLGermanyEnum: string
{
    case DhlGermanyEuropaket = 'dhl_germany_europaket';
    case DhlGermanyPaket = 'dhl_germany_paket';
    case DhlGermanyPaketConnect = 'dhl_germany_paket_connect';
    case DhlGermanyPaketInternational = 'dhl_germany_paket_international';
    case DhlGermanyPaketPriority = 'dhl_germany_paket_priority';
    case DhlGermanyPaketSameday = 'dhl_germany_paket_sameday';
}
