<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * |Token | Service name|
 *
 * |:---|:---|
 * | dhl_express_domestic_express_doc | Domestic Express Doc|
 * | dhl_express_economy_select_doc | Economy Select Doc|
 * | dhl_express_worldwide_nondoc | Express Worldwide Nondoc|
 * | dhl_express_worldwide_doc | Express Worldwide Doc|
 * | dhl_express_worldwide | Worldwide|
 * | dhl_express_worldwide_eu_doc | Express Worldwide EU Doc|
 * | dhl_express_break_bulk_express_doc | Break Bulk Express Doc|
 * | dhl_express_express_9_00_nondoc | Express 9:00 NonDoc|
 * | dhl_express_economy_select_nondoc | Economy Select NonDoc|
 * | dhl_express_break_bulk_economy_doc | Break Bulk Economy Doc|
 * | dhl_express_express_9_00_doc | Express 9:00 Doc|
 * | dhl_express_express_10_30_doc | Express 10:30 Doc|
 * | dhl_express_express_10_30_nondoc | Express 10:30 NonDoc|
 * | dhl_express_express_12_00_doc | Express 12:00 Doc|
 * | dhl_express_europack_nondoc | Europack NonDoc|
 * | dhl_express_express_envelope_doc | Express Envelope Doc|
 * | dhl_express_express_12_00_nondoc | Express 12:00 NonDoc|
 * | dhl_express_express_12_doc | Domestic Express 12:00|
 * | dhl_express_worldwide_b2c_doc | Express Worldwide (B2C) Doc|
 * | dhl_express_worldwide_b2c_nondoc | Express Worldwide (B2C) NonDoc|
 * | dhl_express_medical_express | Medical Express|
 * | dhl_express_express_easy_nondoc | Express Easy NonDoc|
 *
 */
enum ServiceLevelDHLExpressEnum: string
{
    case DhlExpressDomesticExpressDoc = 'dhl_express_domestic_express_doc';
    case DhlExpressEconomySelectDoc = 'dhl_express_economy_select_doc';
    case DhlExpressWorldwideNondoc = 'dhl_express_worldwide_nondoc';
    case DhlExpressWorldwideDoc = 'dhl_express_worldwide_doc';
    case DhlExpressWorldwide = 'dhl_express_worldwide';
    case DhlExpressWorldwideEuDoc = 'dhl_express_worldwide_eu_doc';
    case DhlExpressBreakBulkExpressDoc = 'dhl_express_break_bulk_express_doc';
    case DhlExpressExpress900Nondoc = 'dhl_express_express_9_00_nondoc';
    case DhlExpressEconomySelectNondoc = 'dhl_express_economy_select_nondoc';
    case DhlExpressBreakBulkEconomyDoc = 'dhl_express_break_bulk_economy_doc';
    case DhlExpressExpress900Doc = 'dhl_express_express_9_00_doc';
    case DhlExpressExpress1030Doc = 'dhl_express_express_10_30_doc';
    case DhlExpressExpress1030Nondoc = 'dhl_express_express_10_30_nondoc';
    case DhlExpressExpress1200Doc = 'dhl_express_express_12_00_doc';
    case DhlExpressEuropackNondoc = 'dhl_express_europack_nondoc';
    case DhlExpressExpressEnvelopeDoc = 'dhl_express_express_envelope_doc';
    case DhlExpressExpress1200Nondoc = 'dhl_express_express_12_00_nondoc';
    case DhlExpressExpress12Doc = 'dhl_express_express_12_doc';
    case DhlExpressWorldwideB2cDoc = 'dhl_express_worldwide_b2c_doc';
    case DhlExpressWorldwideB2cNondoc = 'dhl_express_worldwide_b2c_nondoc';
    case DhlExpressMedicalExpress = 'dhl_express_medical_express';
    case DhlExpressExpressEasyNondoc = 'dhl_express_express_easy_nondoc';
}
