<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * |Token | Service name|
 *
 * |:---|:---|
 * | axlehire_same_day | Same Day|
 * | axlehire_next_day | Next Day|
 *
 */
enum ServiceLevelJitsuEnum: string
{
    case AxlehireSameDay = 'axlehire_same_day';
    case AxlehireNextDay = 'axlehire_next_day';
}
