<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * |Token | Service name|
 *
 * |:---|:---|
 * | royal_mail_tracked_letter_boxable_24_no_signature | Royal Mail Tracked Letter-Boxable 24 No Signature|
 * | royal_mail_tracked_letter_boxable_48_no_signature | Royal Mail Tracked Letter-Boxable 48 No Signature|
 * | royal_mail_tracked_24_returns | Royal Mail Tracked Returns 24|
 * | royal_mail_tracked_48_returns | Royal Mail Tracked Returns 48|
 * | royal_mail_special_delivery_guaranteed_1pm | Special Delivery Guaranteed by 1pm
 * | royal_mail_special_delivery_guaranteed_9am | Special Delivery Guaranteed by 9am
 * | royal_mail_24 | RoyalMail 24
 * | royal_mail_48 | RoyalMail 48
 * | royal_mail_signed_for_first_class | Signed for First Class
 * | royal_mail_signed_for_second_class | Signed for Second Class
 * | royal_mail_standard_first_class | Standard First Class
 * | royal_mail_standard_second_class | Standard Second Class
 * | royal_mail_tracked_24_no_signature | Royal Mail Tracked 24 No Signature
 * | royal_mail_tracked_48_no_signature | Royal Mail Ttacked 48 No Signature
 * | royal_mail_intl_bus_mail_lrg_ltr_zone_sort_pri | International Business Mail Large Letter Zone Sort Priority
 * | royal_mail_intl_bus_parcels_tracked_zone_sort | International Business Parcels Tracked Zone Sort
 * | royal_mail_intl_bus_parcels_tracked_country_priced | International Business Parcels Tracked Country Priced
 * | royal_mail_intl_bus_parcels_tracked_signed_zone_srt | International Business Parcels & Signed Zone Sort
 * | royal_mail_24_flat_rate | Royal Mail 24 Parcel Flat Rate
 * | royal_mail_48_flat_rate | Royal Mail 48 Parcel Flat Rate
 *
 */
enum ServiceLevelRoyalMailEnum: string
{
    case RoyalMailTrackedLetterBoxable24NoSignature = 'royal_mail_tracked_letter_boxable_24_no_signature';
    case RoyalMailTrackedLetterBoxable48NoSignature = 'royal_mail_tracked_letter_boxable_48_no_signature';
    case RoyalMailTracked24Returns = 'royal_mail_tracked_24_returns';
    case RoyalMailTracked48Returns = 'royal_mail_tracked_48_returns';
    case RoyalMailSpecialDeliveryGuaranteed1pm = 'royal_mail_special_delivery_guaranteed_1pm';
    case RoyalMailSpecialDeliveryGuaranteed9am = 'royal_mail_special_delivery_guaranteed_9am';
    case RoyalMail24 = 'royal_mail_24';
    case RoyalMail48 = 'royal_mail_48';
    case RoyalMailSignedForFirstClass = 'royal_mail_signed_for_first_class';
    case RoyalMailSignedForSecondClass = 'royal_mail_signed_for_second_class';
    case RoyalMailStandardFirstClass = 'royal_mail_standard_first_class';
    case RoyalMailStandardSecondClass = 'royal_mail_standard_second_class';
    case RoyalMailTracked24NoSignature = 'royal_mail_tracked_24_no_signature';
    case RoyalMailTracked48NoSignature = 'royal_mail_tracked_48_no_signature';
    case RoyalMailIntlBusMailLrgLtrZoneSortPri = 'royal_mail_intl_bus_mail_lrg_ltr_zone_sort_pri';
    case RoyalMailIntlBusParcelsTrackedZoneSort = 'royal_mail_intl_bus_parcels_tracked_zone_sort';
    case RoyalMailIntlBusParcelsTrackedCountryPriced = 'royal_mail_intl_bus_parcels_tracked_country_priced';
    case RoyalMailIntlBusParcelsTrackedSignedZoneSrt = 'royal_mail_intl_bus_parcels_tracked_signed_zone_srt';
    case RoyalMail24FlatRate = 'royal_mail_24_flat_rate';
    case RoyalMail48FlatRate = 'royal_mail_48_flat_rate';
}
