<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/**
 * |Token | Service name|
 *
 * |:---|:---|
 * | same_day | Next Day|
 * | next_day | Next Day|
 *
 */
enum ServiceLevelSwyftEnum: string
{
    case SameDay = 'same_day';
    case NextDay = 'next_day';
}
