<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class ShippoAccountUpdateRequest
{
    /**
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    public string $lastName;

    /**
     *
     * @var string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('company_name')]
    public string $companyName;

    /**
     * @param  string  $email
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  string  $companyName
     * @phpstan-pure
     */
    public function __construct(string $email, string $firstName, string $lastName, string $companyName)
    {
        $this->email = $email;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->companyName = $companyName;
    }
}