<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class TrackingStatusLocationBase
{
    /**
     *
     * @var ?string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $city = null;

    /**
     *
     * @var ?string $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $country = null;

    /**
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     *
     * @var ?string $zip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('zip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $zip = null;

    /**
     * @param  ?string  $city
     * @param  ?string  $country
     * @param  ?string  $state
     * @param  ?string  $zip
     * @phpstan-pure
     */
    public function __construct(?string $city = null, ?string $country = null, ?string $state = null, ?string $zip = null)
    {
        $this->city = $city;
        $this->country = $country;
        $this->state = $state;
        $this->zip = $zip;
    }
}