<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class TracksRequest
{
    /**
     * Name of the carrier of the shipment to track.
     *
     * @var string $carrier
     */
    #[\JMS\Serializer\Annotation\SerializedName('carrier')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $carrier;

    /**
     * A string of up to 100 characters that can be filled with any additional information you want to attach to the object.
     *
     * @var ?string $metadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $metadata = null;

    /**
     * Tracking number to track.
     *
     * @var string $trackingNumber
     */
    #[\JMS\Serializer\Annotation\SerializedName('tracking_number')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $trackingNumber;

    public function __construct()
    {
        $this->carrier = '';
        $this->metadata = null;
        $this->trackingNumber = '';
    }
}