<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class Transaction
{
    /**
     * A URL pointing to the commercial invoice as a 8.5x11 inch PDF file. 
     *
     * A value will only be returned if the Transactions has been processed successfully and if the shipment is international.
     *
     * @var ?string $commercialInvoiceUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('commercial_invoice_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $commercialInvoiceUrl = null;

    /**
     *
     * @var ?CreatedBy $createdBy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_by')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CreatedBy|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreatedBy $createdBy = null;

    /**
     * The estimated time of arrival according to the carrier.
     *
     * @var ?string $eta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('eta')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $eta = null;

    /**
     * Print format of the <a href="https://docs.goshippo.com/docs/shipments/shippinglabelsizes/">label</a>. If empty, will use the default format set from 
     *
     * <a href="https://apps.goshippo.com/settings/labels">the Shippo dashboard.</a>
     *
     * @var ?LabelFileTypeEnum $labelFileType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label_file_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\LabelFileTypeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LabelFileTypeEnum $labelFileType = null;

    /**
     * A URL pointing directly to the label in the format you've set in your settings. 
     *
     * A value will only be returned if the Transactions has been processed successfully.
     *
     * @var ?string $labelUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $labelUrl = null;

    /**
     * $messages
     *
     * @var ?array<ResponseMessage> $messages
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('messages')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Shippo\API\Models\Components\ResponseMessage>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $messages = null;

    /**
     * A string of up to 100 characters that can be filled with any additional information you want to 
     *
     * attach to the object.
     *
     * @var ?string $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $metadata = null;

    /**
     * Date and time of Transaction creation.
     *
     * @var ?\DateTime $objectCreated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_created')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $objectCreated = null;

    /**
     * Unique identifier of the given Transaction object.
     *
     * @var ?string $objectId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $objectId = null;

    /**
     * Username of the user who created the Transaction object.
     *
     * @var ?string $objectOwner
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_owner')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $objectOwner = null;

    /**
     * Indicates the validity of the enclosing object
     *
     * @var ?ObjectStateEnum $objectState
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_state')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\ObjectStateEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ObjectStateEnum $objectState = null;

    /**
     * Date and time of last Transaction update.
     *
     * @var ?\DateTime $objectUpdated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object_updated')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $objectUpdated = null;

    /**
     * Object ID of the Parcel object that is being shipped.
     *
     * @var ?string $parcel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parcel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $parcel = null;

    /**
     * A URL pointing directly to the QR code in PNG format. 
     *
     * A value will only be returned if requested using qr_code_requested flag and the carrier provides such an option.
     *
     * @var ?string $qrCodeUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('qr_code_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $qrCodeUrl = null;

    /**
     * ID of the Rate object for which a Label has to be obtained.  
     *
     * If you purchase a label by calling the transaction endpoint without a rate (instalabel), 
     * this field will be a simplified Rate object in the Transaction model returned from the POST request.
     * </br>Note, only rates less than 7 days old can be purchased to ensure up-to-date pricing.
     *
     * @var CoreRate|string|null $rate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rate')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\CoreRate|string')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public CoreRate|string|null $rate = null;

    /**
     * Indicates the status of the Transaction.
     *
     * @var ?TransactionStatusEnum $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\TransactionStatusEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TransactionStatusEnum $status = null;

    /**
     * Indicates whether the object has been created in test mode.
     *
     * @var ?bool $test
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('test')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $test = null;

    /**
     * The carrier-specific tracking number that can be used to track the Shipment. 
     *
     * A value will only be returned if the Rate is for a trackable Shipment and if the Transactions has been processed successfully.
     *
     * @var ?string $trackingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tracking_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $trackingNumber = null;

    /**
     * Indicates the high level status of the shipment.
     *
     * @var ?TrackingStatusEnum $trackingStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tracking_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\TrackingStatusEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TrackingStatusEnum $trackingStatus = null;

    /**
     * A link to track this item on the carrier-provided tracking website. 
     *
     * A value will only be returned if tracking is available and the carrier provides such a service.
     *
     * @var ?string $trackingUrlProvider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tracking_url_provider')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $trackingUrlProvider = null;

    /**
     * @param  ?string  $commercialInvoiceUrl
     * @param  ?string  $eta
     * @param  ?LabelFileTypeEnum  $labelFileType
     * @param  ?string  $labelUrl
     * @param  ?array<ResponseMessage>  $messages
     * @param  ?string  $metadata
     * @param  ?\DateTime  $objectCreated
     * @param  ?string  $objectId
     * @param  ?string  $objectOwner
     * @param  ?ObjectStateEnum  $objectState
     * @param  ?\DateTime  $objectUpdated
     * @param  ?string  $parcel
     * @param  ?string  $qrCodeUrl
     * @param  CoreRate|string|null  $rate
     * @param  ?TransactionStatusEnum  $status
     * @param  ?bool  $test
     * @param  ?string  $trackingNumber
     * @param  ?TrackingStatusEnum  $trackingStatus
     * @param  ?string  $trackingUrlProvider
     * @param  ?CreatedBy  $createdBy
     */
    public function __construct(?string $commercialInvoiceUrl = null, ?string $eta = null, ?LabelFileTypeEnum $labelFileType = null, ?string $labelUrl = null, ?array $messages = null, ?string $metadata = null, ?\DateTime $objectCreated = null, ?string $objectId = null, ?string $objectOwner = null, ?ObjectStateEnum $objectState = null, ?\DateTime $objectUpdated = null, ?string $parcel = null, ?string $qrCodeUrl = null, CoreRate|string|null $rate = null, ?TransactionStatusEnum $status = null, ?bool $test = null, ?string $trackingNumber = null, ?TrackingStatusEnum $trackingStatus = null, ?string $trackingUrlProvider = null, ?CreatedBy $createdBy = null)
    {
        $this->commercialInvoiceUrl = $commercialInvoiceUrl;
        $this->eta = $eta;
        $this->labelFileType = $labelFileType;
        $this->labelUrl = $labelUrl;
        $this->messages = $messages;
        $this->metadata = $metadata;
        $this->objectCreated = $objectCreated;
        $this->objectId = $objectId;
        $this->objectOwner = $objectOwner;
        $this->objectState = $objectState;
        $this->objectUpdated = $objectUpdated;
        $this->parcel = $parcel;
        $this->qrCodeUrl = $qrCodeUrl;
        $this->rate = $rate;
        $this->status = $status;
        $this->test = $test;
        $this->trackingNumber = $trackingNumber;
        $this->trackingStatus = $trackingStatus;
        $this->trackingUrlProvider = $trackingUrlProvider;
        $this->createdBy = $createdBy;
    }
}