<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class Transaction
{
    /**
     * A URL pointing to the commercial invoice as a 8.5x11 inch PDF file. 
     *
     * A value will only be returned if the Transactions has been processed successfully and if the shipment is international.
     *
     * @var ?string $commercialInvoiceUrl
     */
    #[\JMS\Serializer\Annotation\SerializedName('commercial_invoice_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $commercialInvoiceUrl = null;

    #[\JMS\Serializer\Annotation\SerializedName('created_by')]
    #[\JMS\Serializer\Annotation\Type('Shippo\API\Models\Components\CreatedBy')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreatedBy $createdBy = null;

    /**
     * The estimated time of arrival according to the carrier.
     *
     * @var ?string $eta
     */
    #[\JMS\Serializer\Annotation\SerializedName('eta')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $eta = null;

    /**
     * Print format of the <a href="https://docs.goshippo.com/docs/shipments/shippinglabelsizes/">label</a>. If empty, will use the default format set from 
     *
     * <a href="https://apps.goshippo.com/settings/labels">the Shippo dashboard.</a>
     *
     * @var ?\Shippo\API\Models\Components\LabelFileTypeEnum $labelFileType
     */
    #[\JMS\Serializer\Annotation\SerializedName('label_file_type')]
    #[\JMS\Serializer\Annotation\Type('enum<Shippo\API\Models\Components\LabelFileTypeEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?LabelFileTypeEnum $labelFileType = null;

    /**
     * A URL pointing directly to the label in the format you've set in your settings. 
     *
     * A value will only be returned if the Transactions has been processed successfully.
     *
     * @var ?string $labelUrl
     */
    #[\JMS\Serializer\Annotation\SerializedName('label_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $labelUrl = null;

    /**
     * $messages
     *
     * @var ?array<\Shippo\API\Models\Components\ResponseMessage> $messages
     */
    #[\JMS\Serializer\Annotation\SerializedName('messages')]
    #[\JMS\Serializer\Annotation\Type('array<Shippo\API\Models\Components\ResponseMessage>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $messages = null;

    /**
     * A string of up to 100 characters that can be filled with any additional information you want to 
     *
     * attach to the object.
     *
     * @var ?string $metadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $metadata = null;

    /**
     * Date and time of Transaction creation.
     *
     * @var ?\DateTime $objectCreated
     */
    #[\JMS\Serializer\Annotation\SerializedName('object_created')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $objectCreated = null;

    /**
     * Unique identifier of the given Transaction object.
     *
     * @var ?string $objectId
     */
    #[\JMS\Serializer\Annotation\SerializedName('object_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $objectId = null;

    /**
     * Username of the user who created the Transaction object.
     *
     * @var ?string $objectOwner
     */
    #[\JMS\Serializer\Annotation\SerializedName('object_owner')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $objectOwner = null;

    /**
     * Indicates the validity of the enclosing object
     *
     * @var ?\Shippo\API\Models\Components\ObjectStateEnum $objectState
     */
    #[\JMS\Serializer\Annotation\SerializedName('object_state')]
    #[\JMS\Serializer\Annotation\Type('enum<Shippo\API\Models\Components\ObjectStateEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ObjectStateEnum $objectState = null;

    /**
     * Date and time of last Transaction update.
     *
     * @var ?\DateTime $objectUpdated
     */
    #[\JMS\Serializer\Annotation\SerializedName('object_updated')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $objectUpdated = null;

    /**
     * A URL pointing directly to the QR code in PNG format. 
     *
     * A value will only be returned if requested using qr_code_requested flag and the carrier provides such an option.
     *
     * @var ?string $qrCodeUrl
     */
    #[\JMS\Serializer\Annotation\SerializedName('qr_code_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $qrCodeUrl = null;

    /**
     * ID of the Rate object for which a Label has to be obtained.  
     *
     * If you purchase a label by calling the transaction endpoint without a rate (instalabel), 
     * this field will be a simplified Rate object in the Transaction model returned from the POST request.
     * </br>Note, only rates less than 7 days old can be purchased to ensure up-to-date pricing.
     *
     * @var mixed $rate
     */
    #[\JMS\Serializer\Annotation\SerializedName('rate')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $rate = null;

    /**
     * Indicates the status of the Transaction.
     *
     * @var ?\Shippo\API\Models\Components\TransactionStatusEnum $status
     */
    #[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<Shippo\API\Models\Components\TransactionStatusEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TransactionStatusEnum $status = null;

    /**
     * Indicates whether the object has been created in test mode.
     *
     * @var ?bool $test
     */
    #[\JMS\Serializer\Annotation\SerializedName('test')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $test = null;

    /**
     * The carrier-specific tracking number that can be used to track the Shipment. 
     *
     * A value will only be returned if the Rate is for a trackable Shipment and if the Transactions has been processed successfully.
     *
     * @var ?string $trackingNumber
     */
    #[\JMS\Serializer\Annotation\SerializedName('tracking_number')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $trackingNumber = null;

    /**
     * Indicates the high level status of the shipment.
     *
     * @var ?\Shippo\API\Models\Components\TrackingStatusEnum $trackingStatus
     */
    #[\JMS\Serializer\Annotation\SerializedName('tracking_status')]
    #[\JMS\Serializer\Annotation\Type('enum<Shippo\API\Models\Components\TrackingStatusEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TrackingStatusEnum $trackingStatus = null;

    /**
     * A link to track this item on the carrier-provided tracking website. 
     *
     * A value will only be returned if tracking is available and the carrier provides such a service.
     *
     * @var ?string $trackingUrlProvider
     */
    #[\JMS\Serializer\Annotation\SerializedName('tracking_url_provider')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $trackingUrlProvider = null;

    public function __construct()
    {
        $this->commercialInvoiceUrl = null;
        $this->createdBy = null;
        $this->eta = null;
        $this->labelFileType = null;
        $this->labelUrl = null;
        $this->messages = null;
        $this->metadata = null;
        $this->objectCreated = null;
        $this->objectId = null;
        $this->objectOwner = null;
        $this->objectState = null;
        $this->objectUpdated = null;
        $this->qrCodeUrl = null;
        $this->rate = null;
        $this->status = null;
        $this->test = null;
        $this->trackingNumber = null;
        $this->trackingStatus = null;
        $this->trackingUrlProvider = null;
    }
}