<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


class UserParcelTemplateList
{
    /**
     * $results
     *
     * @var ?array<UserParcelTemplate> $results
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('results')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Shippo\API\Models\Components\UserParcelTemplate>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $results = null;

    /**
     * @param  ?array<UserParcelTemplate>  $results
     */
    public function __construct(?array $results = null)
    {
        $this->results = $results;
    }
}