<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/** Determines the verification option to use for the account registration (Enum: SMS, EMAIL, CALL, INVOICE). */
enum VerificationOption: string
{
    case Sms = 'SMS';
    case Email = 'EMAIL';
    case Call = 'CALL';
    case Invoice = 'INVOICE';
}
