<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


enum WebhookEventTypeEnum: string
{
    case TransactionCreated = 'transaction_created';
    case TransactionUpdated = 'transaction_updated';
    case TrackUpdated = 'track_updated';
    case BatchCreated = 'batch_created';
    case BatchPurchased = 'batch_purchased';
}
