<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/** WebhookPayloadBatch - Content of the webhook posted to the external URL */
class WebhookPayloadBatch
{
    /**
     * Type of event that triggered the webhook.
     *
     * @var ?WebhookEventTypeEnum $event
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('event')]
    #[\Speakeasy\Serializer\Annotation\Type('\Shippo\API\Models\Components\WebhookEventTypeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?WebhookEventTypeEnum $event = null;

    /**
     * Determines whether the webhook is a test webhook or not.
     *
     * @var ?bool $test
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('test')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $test = null;

    /**
     * A string containing the batch object ID, of the form 'batch {batchId} (created|processing complete)'.
     *
     * @var ?string $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $data = null;

    /**
     * @param  ?WebhookEventTypeEnum  $event
     * @param  ?bool  $test
     * @param  ?string  $data
     */
    public function __construct(?WebhookEventTypeEnum $event = null, ?bool $test = null, ?string $data = null)
    {
        $this->event = $event;
        $this->test = $test;
        $this->data = $data;
    }
}