<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Shippo\API\Models\Components;


/** The unit used for weight. */
enum WeightUnitEnum: string
{
    case G = 'g';
    case Kg = 'kg';
    case Lb = 'lb';
    case Oz = 'oz';
}
