name: Retrieve Secrets

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with AWS
        uses: goshippo/shippo-action-workflows/.github/actions/aws_auth@v1.1.0
        with:
          environment: ${{ inputs.environment }}
          oidc-name: shippo-php-sdk-pipeline
          login-to-ecr: false
      
      - name: Get Speakeasy Secrets Manager
        id: get-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            dev-main-speakeasy-api-key
          name-transformation: uppercase
          parse-json-secrets: true

    outputs:
      speakeasy_api_key: ${{ steps.get-secrets.outputs.DEV_MAIN_SPEAKEASY_API_KEY_PHP_API_KEY }}  # Adjust according to your output needs
