name: Validate

on:
  workflow_call:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      SHIPPO_TOKEN: ${{ secrets.SHIPPO_TOKEN }}
    concurrency:
      group: php-sdk-check
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up PHP
        id: setup_php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ./vendor
          key: python-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('setup.py') }}
      - name: Install dependencies
        run: |
          make install
      - name: Check
        run: make check
