name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * *

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: php-sdk-check
    steps:
      - name: Authenticate with AWS
        uses: goshippo/shippo-action-workflows/.github/actions/aws_auth@v1.1.0
        with:
          environment: dev-main
          oidc-name: shippo-php-sdk-pipeline
          login-to-ecr: false

      - name: Get Speakeasy Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            dev-main-speakeasy-api-key
          name-transformation: uppercase
          parse-json-secrets: true

  speakeasy-generate:
    needs: retrieve-secrets
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: ${{ github.event.inputs.force }}
      mode: pr
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ env.DEV_MAIN_SPEAKEASY_API_KEY_PHP_API_KEY }}
